Update pre-push

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -20,56 +20,39 @@
 
 
 
-#!/bin/bash
-set -e
+export PATH=/usr/local/bin:$PATH
 
-SWIFT_LINT=`which swiftlint`
+LINT=$(command -v swiftlint)
 
-if ! [[ -e "${SWIFT_LINT}" ]]; then
-    echo "${SWIFT_LINT} is not installed."
-    exit 0
-fi
-
-echo "SwiftLint $(${SWIFT_LINT} version)"
-
-if [[ $* == *--all* ]]; then
-    ${SWIFT_LINT} autocorrect
-    ${SWIFT_LINT} lint
-    exit 0
-fi
-
-# Always lint AppDelegate to prevent "No lintable files found at paths: ''"
-# caused by a combination --use-script-input-files and --force-exclude
-# See https://github.com/realm/SwiftLint/issues/2619
-export SCRIPT_INPUT_FILE_0="Wire-iOS/Sources/AppDelegate.swift"
-count=1
-
-# make for .. in work with the shitty spaces in our filenames
-OIFS="$IFS"
-IFS=$'\n'
-
-# Changed files not added to stage area yet
-for file_path in $(git diff --diff-filter=d --name-only | grep ".swift$"); do
-    export SCRIPT_INPUT_FILE_$count=$file_path
-    count=$((count + 1))
-done
-
-# Changed files added to stage area
-for file_path in $(git diff --diff-filter=d --name-only --cached | grep ".swift$"); do
-    export SCRIPT_INPUT_FILE_$count=$file_path
-    count=$((count + 1))
-done
-
-# Newly added untracked files
-for file_path in $(git ls-files --others --exclude-standard | grep ".swift$"); do
-    export SCRIPT_INPUT_FILE_$count=$file_path
-    count=$((count + 1))
-done
-
-
-if [ "$count" -ne 0 ]; then
-    export SCRIPT_INPUT_FILE_COUNT=$count
+if [[ -e "${LINT}" ]]; then
+	echo "SwiftLint Start..."
+	echo "$PWD"
 else
-    echo "No files to lint!"
-    exit 0
+	echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
+	exit 1
+fi
+
+RESULT=$($LINT --fix .swiftlint.yml)
+
+if [ -z "$RESULT" ]; then
+	printf "SwiftLint Finished.\n"
+else
+	echo ""
+	printf "SwiftLint Failed. Please check below:\n"
+
+	while read -r line; do
+		FILEPATH=$(echo "$line" | cut -d : -f 1)
+		L=$(echo "$line" | cut -d : -f 2)
+		C=$(echo "$line" | cut -d : -f 3)
+		TYPE=$(echo "$line" | cut -d : -f 4 | cut -c 2-)
+		MESSAGE=$(echo "$line" | cut -d : -f 5 | cut -c 2-)
+		DESCRIPTION=$(echo "$line" | cut -d : -f 6 | cut -c 2-)
+		printf '\n %s\n' "$TYPE"
+		echo "    $FILEPATH:$L:$C"
+		echo "    $MESSAGE - $DESCRIPTION"
+	done <<< "$RESULT"
+
+	printf "\nCOMMIT ABORTED. Please fix them before commiting.\n"
+
+	exit 1
 fi
