chore: Add cherry-pick automatic label and display conflicts WPB-4788

diff --git a/.github/workflows/cherry-pick-from-release-to-develop.yml b/.github/workflows/cherry-pick-from-release-to-develop.yml
--- a/.github/workflows/cherry-pick-from-release-to-develop.yml
+++ b/.github/workflows/cherry-pick-from-release-to-develop.yml
@@ -27,23 +27,25 @@ jobs:
             PR_BRANCH="${{ github.event.pull_request.head.ref }}"
             NEW_BRANCH_NAME="${PR_BRANCH}-cherry-pick"
             echo "New branch name: $NEW_BRANCH_NAME"
-            echo "::set-output name=newBranchName::$NEW_BRANCH_NAME"
+            echo "newBranchName=$NEW_BRANCH_NAME" >> $GITHUB_ENV
+
       - name: Cherry-pick commits
         run: |
             git fetch origin develop:develop
-            git checkout -b ${{ steps.extract.outputs.newBranchName }} develop
+            git checkout -b ${{ env.newBranchName }} develop
             git submodule update --init --recursive || true
-            # Cherry-picking the last commit on the base branch
-            git cherry-pick -x ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true
-            git add .
-            git cherry-pick --continue || true
-            git push origin ${{ steps.extract.outputs.newBranchName }}
+            OUTPUT=$(git cherry-pick ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true)
+            CONFLICTS=$(echo "$OUTPUT" | grep 'CONFLICT' || echo "")
+            if [ -n "$CONFLICTS" ]; then
+                git add .
+                git cherry-pick --continue || true
+            fi
+            git push origin ${{ env.newBranchName }} || (echo "Failed to push to origin" && exit 1)
+            echo "conflicts=$CONFLICTS" >> $GITHUB_ENV
       - name: Create PR
-        id: cpr
-        uses: peter-evans/create-pull-request@v5
-        with:
-            title: ${{ github.event.pull_request.title }}
-            base: develop
-            assignees: ${{ github.event.pull_request.user.login }}
-            branch: "${{ steps.extract.outputs.newBranchName }}"
-            body: "${{ format('Cherry pick from the original PR: \n- #{0}\n\n ---- \n{1}', github.event.pull_request.number, github.event.pull_request.body) }}"
+        env:
+          PR_TITLE: ${{ github.event.pull_request.title }}
+          PR_BRANCH: ${{ env.newBranchName }}
+          PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
+          PR_BODY: "${{ format('Cherry pick from the original PR: \n- #{0}\n\n---- \n\n ⚠️ Conflicts during cherry-pick:\n{1}\n\n{2}', github.event.pull_request.number, env.conflicts, github.event.pull_request.body) }}"
+        run: gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head "$PR_BRANCH" --label "cherry-pick" --assignee "$PR_ASSIGNEE"
