chore: Fix commiter for cherry pick automation WPB-4788 (#529)

diff --git a/.github/workflows/cherry-pick-from-release-to-develop.yml b/.github/workflows/cherry-pick-from-release-to-develop.yml
--- a/.github/workflows/cherry-pick-from-release-to-develop.yml
+++ b/.github/workflows/cherry-pick-from-release-to-develop.yml
@@ -27,17 +27,26 @@ jobs:
             PR_BRANCH="${{ github.event.pull_request.head.ref }}"
             NEW_BRANCH_NAME="${PR_BRANCH}-cherry-pick"
             echo "New branch name: $NEW_BRANCH_NAME"
-            echo "::set-output name=newBranchName::$NEW_BRANCH_NAME"
+            echo "newBranchName=$NEW_BRANCH_NAME" >> $GITHUB_ENV
+      - name: Configure user to bot
+        run: |  
+            git config user.name 'github-actions[bot]'
+            git config user.email 'github-actions[bot]@users.noreply.github.com'
+
       - name: Cherry-pick commits
         run: |
             git fetch origin develop:develop
             git checkout -b ${{ steps.extract.outputs.newBranchName }} develop
             git submodule update --init --recursive || true
-            # Cherry-picking the last commit on the base branch
-            git cherry-pick -x ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true
-            git add .
-            git cherry-pick --continue || true
-            git push origin ${{ steps.extract.outputs.newBranchName }}
+            OUTPUT=$(git cherry-pick ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true)
+            CONFLICTS=$(echo "$OUTPUT" | grep 'CONFLICT' || echo "")
+            if [ -n "$CONFLICTS" ]; then
+                git add .
+                git cherry-pick --continue || true
+            fi
+            git push origin ${{ env.newBranchName }} || (echo "Failed to push to origin" && exit 1)
+            echo "conflicts=$CONFLICTS" >> $GITHUB_ENV
+
       - name: Create PR
         id: cpr
         uses: peter-evans/create-pull-request@v5
